chart/Chart.yaml, chart/templates/rbac.yaml, chart/values.yaml
- the name of the creates ServiceAccount doesn't fit to RBAC definition
- the image name in values.yaml is wrong
- the release 23.0.2 doesn't exists, bump to new major release 25.0.0, and we should tag a new image version and make a release
- tried to install based on the offered Helm chart
=> fix helm rbac

poetry.lock, pyproject.toml
This PR updates the project to use the new `new-pykube` package instead of the outdated `pykube-ng`. The change aims to have a maintainable Version of the Kubernetes library.
- Solves: https://github.com/caas-team/py-kube-downscaler/issues/37
- Updated `pyproject.toml` to replace `pykube-ng` with `new-pykube`.
- Updated `poetry.lock` to reflect the new dependencies.
- Verified that the project builds successfully with the updated dependencies.
- Ran existing tests to ensure that the project functions correctly with `new-pykube`.
=> Enhance/use new-pykube

.github/workflows/python-tests.yml
This change aims to fix the issue where dependabot is unable to run the GitHub Actions workflows due to insufficient permissions. By explicitly granting the necessary permissions in the workflow file, we ensure that dependabot can perform its operations without encountering permission-related errors.
- Updated the `Python Tests` workflow file to include a `permissions` block.
- Granted `read` permissions for `contents` and `write` permissions for `issues`, `checks`, and `pull-requests`.
- Allow workflows to run on all pull requests
None
=> permission adjustments & run on PRs

kube_downscaler/resources/keda.py, kube_downscaler/scaler.py
WIth this PR I fixed a bug that prevented ScaledObjects from being paused if the "paused-replicas" annotation was already present inside the object
If, for some reason, the annotation `autoscaling.keda.sh/paused-replicas` is already present in the ScaledObject, the KubeDownscaler won't process the resource
This bug can happen if the developers incorrectly put this annotation at object creation.
For example this object:
```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
name: cron-scaledobject-2
annotations:
autoscaling.keda.sh/paused-replicas: "2"
spec:
scaleTargetRef:
name: hamster
minReplicaCount: 2
maxReplicaCount: 10
triggers:
- type: cron
metadata:
start: 0 0 * * *
end: 0 6 * * *
desiredReplicaCount: '10'
```
will be logged in this way inside the Kube-Downscaler …
=> Fixed KubeDownscaler Ignoring Keda ScaledObjects if the "paused-replicas" annotation is already present

chart/templates/configmap.yaml
This change aims to address the issue where the `configMapName` key in the kube-downscaler Helm chart does not correctly set the name of the generated ConfigMap. 
- Solves: https://github.com/caas-team/py-kube-downscaler/issues/55
- Updated `templates/configmap.yaml` to use the value of `configMapName` for the ConfigMap name.
- No changes to `templates/deployment.yaml`  - already using the value of `configMapName`.
- Rendered the Helm templates locally using `helm template` to verify that the `configMapName` value is correctly applied in the generated Kubernetes manifests.
=> Ensure configMapName Value is Used Consistently Across Templates

README.md, chart/templates/rbac.yaml, kube_downscaler/cmd.py, kube_downscaler/scaler.py, tests/test_autoscale_resource.py, tests/test_cmd.py, tests/test_ignore_if_labels_dont_match.py, tests/test_scaler.py
Hi Everyone,
Today I added to the project the option to Downscale DaemonSets! DaemonSets are usually not among the highest priorities when scaling down the cluster during non-working hours because they often support vital processes for the cluster (logging, monitoring and so on) however, it may be the case that not all DaemonSets are needed for applications that remain active during non-working hours. Turning off these DaemonSets could be very convenient especially when combined with using Karpenter
The new feature acts in this way:
Downtime Hours: Add to the DaemonSet a Node Selector that cannot be satisfied called `kube-downscaler-non-existent=true
`Uptime Hours: Remove from the DaemonSet the `kube-downscaler-non-existent=true` Node Selector
added the logic explained above inside the …
=> New Feature - Downscaling DaemonSet 

chart/values.yaml
The default downtime minimum replicas is 0; and the minReplicas field can't be 0 in HorizontalPodAutscaler.
Hence the default installation crashes when there are HorizontalPodAutoscalers with unspecified downscaler/downtime-replicas annotation.
Disable the downscaling of HorizontalPodAutoscalers by default (it cannot work by default as it requires manual annotations to be functional).
1. deploy an HPA with no annotation
2. deploy py-kube-downscaler with default Helm variables
3. verify that py-kube-downscaler does not crash when downscaling happens
=> fix: disable HPA downscaling by default

README.md, chart/values.yaml, kube_downscaler/cmd.py
This small change helps migrate from the version of the Kubedownscaler published on Codeberg to the new version maintained here on Github.
The old namespace name "kube-downscaler" is added among the default values ​​inside the chart helm "Excluded Namespace" section and inside the cmd.py class.
Refactored docs to explain how to migrate from the old Codeberg repo
`cmd.py`
`values.yaml `
`readme`
as described in the section above 
Unit tests
=> Facilitates backward compatibility

README.md, kube_downscaler/scaler.py, tests/test_grace_period.py
This feature introduces the ability to override the global grace period defined by the `--grace-period` argument in the main deployment. By using the new `downscaler/grace-period` annotation, you can set a specific grace period for individual resources.
**Important**: The annotation will only override the global grace period if the value specified in the annotation is shorter than the globally defined grace period. This ensures that the feature cannot be misused by users to extend the grace period beyond the intended limit.
- a new annotation was introduced: `downscaler/grace-period`
- `within_grace_period` and `within_grace_period_namespace` functions where refactored to implement the logic described above
Unit tests inside `test_grace_period.py`
=> New Feature: New Downscaler/Grace-Period Annotation To Override Global Grace Period for Individual Resources

README.md, kube_downscaler/cmd.py, kube_downscaler/main.py, kube_downscaler/scaler.py, tests/test_autoscale_resource.py, tests/test_scaler.py
The `--upscale-target-only` is an advanced argument designed to ensure that only those namespaces currently targeted by the downscaler will be upscaled during "wake up" times. 
Consider a scenario where the downscaler is initially configured to manage namespaces A, B, and C. If the configuration is later updated to target only namespaces B and C, this parameter will ensure that namespace A, which is not in the new target, remains downscaled. Without this parameter, namespace A could will be upscaled following the original behavior of the tool
This behavior is useful in cases where precise control over upscaling is required. It will let the user choose the original behavior or the new behavior introduced with pull requests #80  
TLDR:
**Default Behavior:** If the `--upscale-target-only` …
=> New Argument: Upscale Target Only

kube_downscaler/scaler.py
The ScaledObject fix https://github.com/caas-team/py-kube-downscaler/pull/87 introduced yesterday handles the downscaling properly.
However this commit https://github.com/caas-team/py-kube-downscaler/commit/71c465f61f520c6528203164740b08d9026c17d0 breaks upscaling of ScaledObject when there was no `autoscaling.keda.sh/paused-replicas` annotation set before and therefore annotation `downscaler/original-pause-replicas` is missing.
```
2024-08-23 08:11:35,472 ERROR: Failed to process ScaledObject wp-bedrock-sample/wp-bedrock-sample-wordpress-bedrock: 'downscaler/original-pause-replicas'
Traceback (most recent call last):                                                                                                                             
File "/kube_downscaler/scaler.py", line 934, in …
```
=> Fix KEDA ScaledObject KeyError on upscaling

chart/Chart.yaml, chart/templates/rbac.yaml, kube_downscaler/resources/keda.py, tests/test_autoscale_resource.py, tests/test_scaler.py
1. Enhanced Tests For Scaled Objects Downscaling/Upscaling. 
2. Added inside keda.py a logic to handle "autoscaling.keda.sh/paused-replicas" is None 
The second behavior described above only happens inside test classes, this is for a reason:
- In real life Kubernetes will delete the annotation when it is set to None 
- In Python it will be assigned the real None type
Enhanced Tests For Scaled Objects Downscaling/Upscaling
Unit Tests
=> Enhanced Tests For Scaled Objects Downscaling/Upscaling

chart/templates/rbac.yaml
This update fixes 403 that error that occurs if you deploy KD with the helm chart and include job resources. 
This error occurred because the service account did not had permission to manage **job** resources.
On ClusterRole at the helm template **rbac.yaml** added the **jobs** resource next to **cronjobs**.
None
=> Added missing job resource on clusterrole

.pre-commit-config.yaml, README.md, chart/Chart.yaml
This pull request aims to bump the version numbers to make a new release in order to fix https://github.com/caas-team/py-kube-downscaler/issues/97.
* Bumped appVersion and version numbers.
* Made a few changes to the README.md that were overdue
* Removed outdated exclusion path from pre-commit-config.yaml
There might still be some things that are not quite up to date. I will take a look when i have the time. For the meantime this doesn't pose as a big problem.
=> Chore/bump to24.10.0

README.md, kube_downscaler/resources/keda.py, kube_downscaler/scaler.py, tests/test_autoscale_resource.py, tests/test_resources.py, tests/test_scaler.py
Actually ScaledObject doesn't support "downscaler/downtime-replicas" annotation. See issue #96 
- Refactored Keda ScaledObject resource class in order to support "downscaler/downtime-replicas" annotation
- Refactored scaler.py class in order to support "downscaler/downtime-replicas" annotation for Keda
- Made Keda ScaledObject more clear
- Added and Refactored Keda Unit Tests
- Refactored Docs
- Unit Tests
=> Added ScaledObject Support For Downscaler/Downtime-Replicas Annotation

kube_downscaler/helper.py, kube_downscaler/scaler.py, tests/test_scaler.py
The newly introduced `--api-server-timeout` is not applying the user-defined timeout to the Kubeconfig created by Pykube because the monkey patching occurs after the Kubeconfig has been created.
Refactored the logic, the `--api-server-timeout` will inject its value thourgh the HTTPObject Constructor instead of monkeypatching PyKube library
- Unit Tests
- Built a Custom Imaged and Tested
=> Fix: Api Server Timeout Argument Doesn't Override Default Timeout Value

chart/templates/deployment.yaml
ImagePullSecret is referred to as customizable in the chart's values.yaml , yet it is not managed in the deployment template.
We need this fix since we use a privately hosted registry with private repos in our organization.
ImagePullSecret added to the deployment template.
- Unit Tests
=> Fix: Added imagePullSecret customization support

tests/test_scaler.py
After merging the `test_scale_custom_timeout` was missing the `max_retries_on_conflict` argument
inserting `max_retries_on_conflict` argument inside the test
Unit tests
=> Fix: Test_Scale_Custom_Timeout After Merging

Dockerfile
As stated in issue #114 due to the Python version the project is using right now, the Docker image suffers from the following vulnerabilities:
- https://github.com/advisories/GHSA-cx63-2mw6-8hw5 Severity High - setuptools
- https://github.com/advisories/GHSA-mq26-g339-26xf Severity Medium - pip
- Built a new image with Python 3.12.7
- Built the new image and tested inside a test cluster
- Unit Tests
=> Chore: Update Python Version to 3.12.7

.github/workflows/python-tests.yml
Since we bumped the minimum required Python version to [3.9 in pyproject.toml](https://github.com/caas-team/py-kube-downscaler/pull/112/commits/9472cdac13a5d80c453bfb37cbcf92dd53159671), we should align our Python test workflow to use the same version.
- Updated the Python version in the GitHub Actions workflow for tests from `3.8` to `3.9`.
- Verified that the GitHub Actions workflow runs successfully with the updated Python version.
=> Chore: Adjust Python Version

.pre-commit-config.yaml, poetry.lock
As with new-pykube, dependabot stated vulnerabilities with jinja2 in https://github.com/caas-team/py-kube-downscaler/security/dependabot/11 and https://github.com/caas-team/py-kube-downscaler/security/dependabot/12. This PR fixes this and updates all other dependencies while at it.
- Updating certifi (2024.8.30 -> 2024.12.14)
- Updating charset-normalizer (3.4.0 -> 3.4.1)
- Updating urllib3 (2.2.3 -> 2.3.0)
- Updating coverage (7.6.9 -> 7.6.10)
- Updating identify (2.6.3 -> 2.6.4)
- Updating jinja2 (3.1.4 -> 3.1.5)
- Updating mypy (1.13.0 -> 1.14.1)
- Updating new-pykube (24.12.0 -> 25.1.0)
- Updated the pre-commit hooks
Ran the python tests and pre-commit successfully.
=> chore: update dependencies to fix dependabot findings

chart/Chart.yaml, chart/templates/deployment.yaml
`imagePullPolicy` has been added to the helm chart  at the correct level of indentation. This is leading to outOfSync errors in ArgoCD. 
Moves imagePullPolicy to the correct location in the `deployment.yaml` file of the helm chart
=> fix: move imagePullPolicy to container definition

chart/templates/rbac.yaml
When using `constrainedDownscaler=true` with multiple `constrainedNamespaces` defined, the Helm Chart was unable to correctly separate Roles and RoleBindings for each namespace (#147)
- Added a separator after the RoleBinding
- Built the Helm Chart in this way:
`helm template . --set constrainedDownscaler=true --set constrainedNamespaces[0]=kube-system --set constrainedNamespaces[1]=monitoring --set constrainedNamespaces[2]=test
`
=> Fix/Broken Helm Chart When Using Multiple Constrained Namespaces

README.md, kube_downscaler/scaler.py, tests/test_scaler.py
As described #154, the downscaler is actually not able to handle values written as percentages such as:
```yaml
spec:
maxUnavailable: 10%
selector:
matchLabels:
app: test-app
```
- Displaying warning log when scaling PodDisruptionBudgets that falls in the description made above
- Improved documentation
- Added unit tests with percentage
- Unit Tests
=> Fix: Behavior of Pod Disruption Budgets With Percentages

README.md, kube_downscaler/cmd.py, kube_downscaler/helper.py, kube_downscaler/main.py, kube_downscaler/scaler.py, tests/test_autoscale_resource.py, tests/test_scaler.py
As addressed in the issue #159 actually KubeDownscaler is not able to scale PodDisruptionBudgets with fields specified as a percentage. This PR aims at fixing this limitation
- The main algorithm is now able to distinguish and process both float and integer values
- `get_replicas`, `scale_up` and `scale_down` functions are now able to process float values
- Improved documentation
Limitation: even though PodDisruptionBudgets can now be processed if they have fields specified as a percentage, if either the global argument --downtime-replicas or the workload/namespace annotation downscaler/downtime-replicas is set to a value greater than 0, the resource will be excluded. This is because the percentage is converted to a float value `0<=x<=1`
- Refactored UnitTests
=> Feat: Scale PodDisruptionBudgets With Percentage Values

Dockerfile, chart/Chart.yaml, poetry.lock, pyproject.toml
July 2025 release fixes some vulnerabilities and bumps dependencies version
The main change concerns the `urllib3` library, which was recently affected by a vulnerability. Full list of upgrades below:
- Updating typing-extensions (4.14.0 -> 4.14.1)
- Updating pygments (2.19.1 -> 2.19.2)
- Updating certifi (2025.4.26 -> 2025.7.14)
- Updating pytest (8.4.0 -> 8.4.1)
- Updating urllib3 (2.4.0 -> 2.5.0)
- Updating mypy (1.16.0 -> 1.17.0)
- Updating new-pykube (25.6.0 -> 25.7.0)
The docker base image was updated from `3.12.10-alpine3.22` to `3.12.11-alpine3.22` to fix minor vulnerabilities
- Unit tests
=>  Chore: Release 25.7.0
