.github/workflows/docker-build.yml
- transferred build and push action from https://github.com/caas-team/kube-downscaler
=> update build action

.github/workflows/docker-build.yml
- changed condition for building and pushing images
=> fix: build on main only

kube_downscaler/scaler.py
These are the pull requests from https://codeberg.org/hjacobs/kube-downscaler/pulls/64 and https://codeberg.org/hjacobs/kube-downscaler/pulls/65.
=> Fix existing issues with labels and resources

.github/workflows/helm-build.yml
fixes: https://github.com/caas-team/py-kube-downscaler/issues/16
- linting helm chart
- package and push to ghcr and mtr
- could be also signed if necessary
=> add helm build wf

chart/Chart.yaml
- Refers to: #29
appVersion bumped in Chart.yaml in preperation for new release
=> bump appVersion

chart/Chart.yaml, chart/templates/deployment.yaml
This PR addresses issue #31. It adds support for tolerations in the Helm chart to handle autoscaling with Karpenter.
Thanks to @remmercier for their contribution.
- Added tolerations handling in the `template/deployment.yaml` file:
```yaml
{{- with .Values.tolerations }}
tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
```
- `values.yaml` placeholder for tolerations already existed.
- Rendered the Helm templates locally using `helm template` to verify the tolerations are correctly included in the generated YAML.
=> Feat/helmchart  taking account about tolerations values into deployment template

chart/Chart.yaml
- Solves: https://github.com/caas-team/py-kube-downscaler/issues/28
appVersion bumped in Chart.yaml in preperation for new release
=> Chore/bump version 24.5.2

chart/Chart.yaml
- Refers to: https://github.com/caas-team/py-kube-downscaler/issues/55
- Bumped chart version to 0.2.2
=> bump chart version > 0.2.2

README.md
Refactoring Docs to include an explaination of the recent updates. Refactoring Docs layout
Refactored Docs
=> Refactoring Docs

chart/Chart.yaml, poetry.lock, pyproject.toml
- Solves: https://github.com/caas-team/py-kube-downscaler/issues/64
- updated appVersion & ChartVersion
- updated new-pykube package version
Existing tests
=> Bump version to 24.7.0

README.md
- Explained Overlapping Times and how to correctly configure recurring specifications
- Explained Overlapping Times and how to correctly configure recurring specifications
Tests not needed
=> Documentation Refactoring

chart/templates/configmap.yaml, chart/templates/deployment.yaml, chart/templates/rbac.yaml, chart/values.yaml
Cleaning and add capabilities to set affinity and nodeSelector on deployment ressource
* Add capabilities to set affinity and nodeSelector on deployment ressource
* Remove usued values autoscaling and service
* Removing unnecessary variable Release.Namespace on ressources
* Deployment with default values
* Deployment with affinity and nodeselector values
=> [Helm chart] clean unused values and setup nodeselector and affinity

kube_downscaler/scaler.py
https://github.com/caas-team/py-kube-downscaler/issues/86
Safely check if the key exists before accessing it
None so far
=> Fix KEDA ScaledObject KeyError

kube_downscaler/scaler.py, tests/test_autoscale_resource.py
#86 
Safely check if the key exists before accessing it
added unit tests for scaled object
=> Fix KEDA ScaledObject KeyError - Scale Up

chart/Chart.yaml
Updated Chart Version And App Version to 0.2.6 and 24.9.0 (next release)
Updated Chart Version And App Version to 0.2.6 and 24.9.0
Unit Tests
=> Updated Chart Version To 24.9.0

README.md
We changed the workspace url and name, which requires us to change the inviter url to match.
=> chore: change slack inviter url to kube-downscaler

chart/Chart.yaml
Bump version to 24.10.1
- Added Support for `downscaler/downtime-replicas` inside ScaledObject
- Updated Dependencies 
- Unit Tests
- Manual Tests Inside Kubernetes
=> Chore: Version 24.10.1

chart/templates/rbac.yaml
This pr aims to fix the behaviour of always trying to create a serviceaccount even when create is set to false.
Added if statement to rbac.yaml.
=> fix: serviceaccount creation

chart/Chart.yaml, pyproject.toml
Releasing Version 24.12.0
Bumped AppVersion and ChartVersion to 24.12.0
- Unit Tests
- Cluster Tests
=> Chore: Release 24.12.0 

pyproject.toml
I forgot to bump the pyproject.toml
- chore: bump version
=> chore: bump version in pyproject.toml

chart/Chart.yaml, chart/templates/configmap.yaml, chart/templates/deployment.yaml, chart/templates/rbac.yaml
Following what we did here https://github.com/caas-team/GoKubeDownscaler/issues/127 to keep the chart clean and understandable 
Added `{{ .Release.Namespace }}` in the objects
- Unit Tests
=>  Added {{ .Release.Namespace }} Inside Helm Chart

pyproject.toml
Bumps the downscalers version to 25.3.1 for the new release.
* bump project version for new release
=> chore: bump project version for new release

chart/Chart.yaml, pyproject.toml
Release 25.3.2 to fix the problem in the Helm Chart found in #147 
- Fixed the problem in the Helm Chart #148 
- Unit Tests
=> feat: new release for helm chart fix

chart/templates/deployment.yaml, chart/values.yaml
I would like to be able to configure the revisionHistoryLimit
helm chart : add revisionHistoryLimit
helm template
=> helm chart add revisionHistoryLimit
